/** Database + ORM detection rules */
export const DB_NPM_RULES = [
  { pkg: "pg", name: "PostgreSQL", orm: null },
  { pkg: "postgres", name: "PostgreSQL", orm: null },
  { pkg: "mysql", name: "MySQL", orm: null },
  { pkg: "mysql2", name: "MySQL", orm: null },
  { pkg: "mariadb", name: "MariaDB", orm: null },
  { pkg: "sqlite3", name: "SQLite", orm: null },
  { pkg: "better-sqlite3", name: "SQLite", orm: null },
  { pkg: "mongodb", name: "MongoDB", orm: null },
  { pkg: "mongoose", name: "MongoDB", orm: "Mongoose" },
  { pkg: "ioredis", name: "Redis", orm: null },
  { pkg: "redis", name: "Redis", orm: null },
  { pkg: "@prisma/client", name: null, orm: "Prisma" },
  { pkg: "prisma", name: null, orm: "Prisma" },
  { pkg: "typeorm", name: null, orm: "TypeORM" },
  { pkg: "sequelize", name: null, orm: "Sequelize" },
  { pkg: "knex", name: null, orm: "Knex" },
  { pkg: "drizzle-orm", name: null, orm: "Drizzle ORM" },
  { pkg: "mikro-orm", name: null, orm: "MikroORM" },
  { pkg: "@mikro-orm/core", name: null, orm: "MikroORM" },
  { pkg: "objection", name: null, orm: "Objection.js" },
  { pkg: "firebase", name: "Firebase", orm: null },
  { pkg: "firebase-admin", name: "Firebase", orm: null },
  { pkg: "@supabase/supabase-js", name: "Supabase", orm: null },
  { pkg: "@neondatabase/serverless", name: "Neon (PostgreSQL)", orm: null },
  { pkg: "@planetscale/database", name: "PlanetScale", orm: null },
  { pkg: "@aws-sdk/client-dynamodb", name: "DynamoDB", orm: null },
  { pkg: "cassandra-driver", name: "Cassandra", orm: null },
  { pkg: "@elastic/elasticsearch", name: "Elasticsearch", orm: null },
  { pkg: "elasticsearch", name: "Elasticsearch", orm: null },
  { pkg: "neo4j-driver", name: "Neo4j", orm: null },
  { pkg: "oracledb", name: "Oracle", orm: null },
  { pkg: "tedious", name: "Microsoft SQL Server", orm: null },
  { pkg: "mssql", name: "Microsoft SQL Server", orm: null },
  { pkg: "couchbase", name: "Couchbase", orm: null },
  { pkg: "nano", name: "CouchDB", orm: null },
  { pkg: "faunadb", name: "FaunaDB", orm: null },
  { pkg: "@azure/cosmos", name: "Azure Cosmos DB", orm: null },
];

export const DB_PYTHON_RULES = [
  { pkg: "psycopg2", name: "PostgreSQL", orm: null },
  { pkg: "psycopg2-binary", name: "PostgreSQL", orm: null },
  { pkg: "psycopg", name: "PostgreSQL", orm: null },
  { pkg: "asyncpg", name: "PostgreSQL", orm: null },
  { pkg: "mysqlclient", name: "MySQL", orm: null },
  { pkg: "pymysql", name: "MySQL", orm: null },
  { pkg: "aiomysql", name: "MySQL", orm: null },
  { pkg: "pymongo", name: "MongoDB", orm: null },
  { pkg: "motor", name: "MongoDB", orm: null },
  { pkg: "redis", name: "Redis", orm: null },
  { pkg: "sqlalchemy", name: null, orm: "SQLAlchemy" },
  { pkg: "django", name: null, orm: "Django ORM" },
  { pkg: "tortoise-orm", name: null, orm: "Tortoise ORM" },
  { pkg: "peewee", name: null, orm: "Peewee" },
  { pkg: "databases", name: null, orm: "Encode Databases" },
  { pkg: "firebase-admin", name: "Firebase", orm: null },
  { pkg: "elasticsearch", name: "Elasticsearch", orm: null },
  { pkg: "cassandra-driver", name: "Cassandra", orm: null },
  { pkg: "neo4j", name: "Neo4j", orm: null },
  { pkg: "cx-Oracle", name: "Oracle", orm: null },
  { pkg: "oracledb", name: "Oracle", orm: null },
  { pkg: "pyodbc", name: "ODBC / SQL Server", orm: null },
];

export const DB_COMPOSER_RULES = [
  { pkg: "illuminate/database", name: null, orm: "Eloquent" },
  { pkg: "doctrine/orm", name: null, orm: "Doctrine" },
];

export const DB_URL_PATTERNS = [
  { match: /postgres(ql)?:\/\//i, name: "PostgreSQL" },
  { match: /mysql:\/\//i, name: "MySQL" },
  { match: /mariadb:\/\//i, name: "MariaDB" },
  { match: /mongodb(\+srv)?:\/\//i, name: "MongoDB" },
  { match: /redis:\/\//i, name: "Redis" },
  { match: /sqlite:\/\//i, name: "SQLite" },
  { match: /sqlserver:\/\/|mssql:\/\//i, name: "Microsoft SQL Server" },
  { match: /oracle:\/\//i, name: "Oracle" },
  { match: /cassandra:\/\//i, name: "Cassandra" },
  { match: /neo4j:\/\//i, name: "Neo4j" },
  { match: /DATABASE_URL\s*=\s*.*postgres/i, name: "PostgreSQL" },
  { match: /DATABASE_URL\s*=\s*.*mysql/i, name: "MySQL" },
  { match: /MONGO_URI|MONGODB_URI/i, name: "MongoDB" },
  { match: /REDIS_URL/i, name: "Redis" },
  { match: /FIREBASE_/i, name: "Firebase" },
  { match: /SUPABASE_/i, name: "Supabase" },
];

export const DB_FILE_RULES = [
  { match: /(^|\/)prisma\/schema\.prisma$/i, name: null, orm: "Prisma" },
  { match: /(^|\/)schema\.prisma$/i, name: null, orm: "Prisma" },
  { match: /(^|\/)drizzle\.config\.(ts|js)$/i, name: null, orm: "Drizzle ORM" },
  { match: /(^|\/)ormconfig\.(js|ts|json)$/i, name: null, orm: "TypeORM" },
  { match: /(^|\/)alembic\.ini$/i, name: null, orm: "SQLAlchemy / Alembic" },
  { match: /(^|\/).*\.sqlite3?$/i, name: "SQLite", orm: null },
  { match: /(^|\/)firebase\.json$/i, name: "Firebase", orm: null },
];

export const PRISMA_PROVIDER_MAP = {
  postgresql: "PostgreSQL",
  postgres: "PostgreSQL",
  mysql: "MySQL",
  sqlite: "SQLite",
  sqlserver: "Microsoft SQL Server",
  mongodb: "MongoDB",
  cockroachdb: "CockroachDB",
};

export const DOTNET_DB_RULES = [
  { match: /PackageReference Include="Dapper"/i, name: null, orm: "Dapper" },
  { match: /\busing Dapper\b|Dapper\./i, name: null, orm: "Dapper" },
  { match: /Microsoft\.EntityFrameworkCore|EntityFrameworkCore/i, name: null, orm: "Entity Framework Core" },
  { match: /UseNpgsql|Npgsql/i, name: "PostgreSQL", orm: null },
  { match: /UseSqlServer/i, name: "Microsoft SQL Server", orm: null },
  { match: /UseSqlite/i, name: "SQLite", orm: null },
  { match: /UseMySql|Pomelo/i, name: "MySQL", orm: null },
  { match: /SqlConnection|Microsoft\.Data\.SqlClient|System\.Data\.SqlClient/i, name: "Microsoft SQL Server", orm: null },
  { match: /MongoClient|MongoDB\.Driver/i, name: "MongoDB", orm: null },
  { match: /StackExchange\.Redis/i, name: "Redis", orm: null },
];

export const JAVA_DB_RULES = [
  { match: /spring\.datasource\.url\s*[:=].*postgres/i, name: "PostgreSQL", orm: "Spring Data / JPA" },
  { match: /spring\.datasource\.url\s*[:=].*mysql/i, name: "MySQL", orm: "Spring Data / JPA" },
  { match: /hibernate/i, name: null, orm: "Hibernate" },
  { match: /mongodb:\/\//i, name: "MongoDB", orm: "Spring Data MongoDB" },
];
