/**
 * Framework / language / tooling detection rules.
 * type: "file" | "dep" | "content" | "ext"
 */
export const LANGUAGE_BY_EXT = {
  ".js": "JavaScript",
  ".jsx": "JavaScript",
  ".mjs": "JavaScript",
  ".cjs": "JavaScript",
  ".ts": "TypeScript",
  ".tsx": "TypeScript",
  ".py": "Python",
  ".java": "Java",
  ".kt": "Kotlin",
  ".kts": "Kotlin",
  ".cs": "C#",
  ".fs": "F#",
  ".vb": "VB.NET",
  ".go": "Go",
  ".rs": "Rust",
  ".php": "PHP",
  ".rb": "Ruby",
  ".swift": "Swift",
  ".dart": "Dart",
  ".vue": "Vue",
  ".svelte": "Svelte",
  ".scala": "Scala",
  ".clj": "Clojure",
  ".ex": "Elixir",
  ".exs": "Elixir",
  ".hs": "Haskell",
  ".lua": "Lua",
  ".r": "R",
  ".m": "Objective-C",
  ".mm": "Objective-C++",
  ".cpp": "C++",
  ".cc": "C++",
  ".c": "C",
  ".h": "C/C++ Header",
  ".hpp": "C++",
  ".sol": "Solidity",
  ".sql": "SQL",
  ".graphql": "GraphQL",
  ".gql": "GraphQL",
};

/** Framework rules from file presence */
export const FRAMEWORK_FILE_RULES = [
  { match: /(^|\/)next\.config\.(js|mjs|ts|cjs)$/i, name: "Next.js", category: "framework" },
  { match: /(^|\/)angular\.json$/i, name: "Angular", category: "framework" },
  { match: /(^|\/)nuxt\.config\.(js|ts|mjs)$/i, name: "Nuxt", category: "framework" },
  { match: /(^|\/)svelte\.config\.(js|ts|mjs)$/i, name: "SvelteKit", category: "framework" },
  { match: /(^|\/)astro\.config\.(js|mjs|ts)$/i, name: "Astro", category: "framework" },
  { match: /(^|\/)remix\.config\.(js|ts)$/i, name: "Remix", category: "framework" },
  { match: /(^|\/)gatsby-config\.(js|ts|mjs)$/i, name: "Gatsby", category: "framework" },
  { match: /(^|\/)nest-cli\.json$/i, name: "NestJS", category: "framework" },
  { match: /(^|\/)pubspec\.yaml$/i, name: "Flutter", category: "framework" },
  { match: /(^|\/)manage\.py$/i, name: "Django", category: "framework" },
  { match: /(^|\/)artisan$/i, name: "Laravel", category: "framework" },
  { match: /(^|\/)Gemfile$/i, name: "Ruby", category: "language-tool" },
  { match: /(^|\/)config\/routes\.rb$/i, name: "Ruby on Rails", category: "framework" },
  { match: /(^|\/)go\.mod$/i, name: "Go", category: "language-tool" },
  { match: /(^|\/)Cargo\.toml$/i, name: "Rust", category: "language-tool" },
  { match: /(^|\/)composer\.json$/i, name: "PHP Composer", category: "language-tool" },
  { match: /(^|\/)pom\.xml$/i, name: "Maven", category: "language-tool" },
  { match: /(^|\/)build\.gradle(\.kts)?$/i, name: "Gradle", category: "language-tool" },
  { match: /(^|\/).*\.sln$/i, name: ".NET", category: "framework" },
  { match: /(^|\/).*\.csproj$/i, name: ".NET / ASP.NET", category: "framework" },
  { match: /(^|\/)appsettings\.json$/i, name: "ASP.NET Core", category: "framework" },
  { match: /(^|\/)Program\.cs$/i, name: "ASP.NET Core", category: "framework" },
  { match: /(^|\/)Startup\.cs$/i, name: "ASP.NET", category: "framework" },
  { match: /(^|\/)AndroidManifest\.xml$/i, name: "Android", category: "framework" },
  { match: /(^|\/)Podfile$/i, name: "CocoaPods / iOS", category: "framework" },
  { match: /(^|\/)Package\.swift$/i, name: "Swift Package", category: "framework" },
  { match: /(^|\/)Dockerfile$/i, name: "Docker", category: "other" },
  { match: /(^|\/)docker-compose\.(yml|yaml)$/i, name: "Docker Compose", category: "other" },
  { match: /(^|\/)compose\.(yml|yaml)$/i, name: "Docker Compose", category: "other" },
  { match: /(^|\/)vercel\.json$/i, name: "Vercel", category: "other" },
  { match: /(^|\/)netlify\.toml$/i, name: "Netlify", category: "other" },
  { match: /(^|\/)firebase\.json$/i, name: "Firebase", category: "other" },
  { match: /(^|\/)serverless\.(yml|yaml|ts|js)$/i, name: "Serverless Framework", category: "other" },
  { match: /(^|\/)vercel\.json$/i, name: "Vercel", category: "other" },
  { match: /(^|\/)vite\.config\.(js|ts|mjs|cjs)$/i, name: "Vite", category: "other" },
  { match: /(^|\/)webpack\.config\.(js|ts|mjs)$/i, name: "Webpack", category: "other" },
  { match: /(^|\/)tailwind\.config\.(js|ts|cjs|mjs)$/i, name: "Tailwind CSS", category: "other" },
  { match: /(^|\/)prisma\/schema\.prisma$/i, name: "Prisma", category: "other" },
  { match: /(^|\/)schema\.prisma$/i, name: "Prisma", category: "other" },
  { match: /(^|\/)\.github\/workflows\//i, name: "GitHub Actions", category: "other" },
  { match: /(^|\/)Jenkinsfile$/i, name: "Jenkins", category: "other" },
  { match: /(^|\/)\.gitlab-ci\.yml$/i, name: "GitLab CI", category: "other" },
  { match: /(^|\/)capacitor\.config\.(ts|json)$/i, name: "Capacitor", category: "framework" },
  { match: /(^|\/)ionic\.config\.json$/i, name: "Ionic", category: "framework" },
  { match: /(^|\/)electron\.config\./i, name: "Electron", category: "framework" },
  { match: /(^|\/)tauri\.conf\.json$/i, name: "Tauri", category: "framework" },
];

/** package.json dependency → framework */
export const NPM_DEP_RULES = [
  { pkg: "next", name: "Next.js" },
  { pkg: "react", name: "React" },
  { pkg: "react-dom", name: "React" },
  { pkg: "react-native", name: "React Native" },
  { pkg: "@angular/core", name: "Angular" },
  { pkg: "vue", name: "Vue.js" },
  { pkg: "nuxt", name: "Nuxt" },
  { pkg: "svelte", name: "Svelte" },
  { pkg: "@sveltejs/kit", name: "SvelteKit" },
  { pkg: "express", name: "Express" },
  { pkg: "fastify", name: "Fastify" },
  { pkg: "koa", name: "Koa" },
  { pkg: "@nestjs/core", name: "NestJS" },
  { pkg: "hapi", name: "Hapi" },
  { pkg: "@hapi/hapi", name: "Hapi" },
  { pkg: "gatsby", name: "Gatsby" },
  { pkg: "astro", name: "Astro" },
  { pkg: "@remix-run/react", name: "Remix" },
  { pkg: "electron", name: "Electron" },
  { pkg: "@tauri-apps/api", name: "Tauri" },
  { pkg: "expo", name: "Expo" },
  { pkg: "expo-router", name: "Expo Router" },
  { pkg: "@ionic/react", name: "Ionic" },
  { pkg: "@ionic/angular", name: "Ionic" },
  { pkg: "@ionic/vue", name: "Ionic" },
  { pkg: "solid-js", name: "SolidJS" },
  { pkg: "ember-source", name: "Ember.js" },
  { pkg: "jquery", name: "jQuery" },
  { pkg: "backbone", name: "Backbone.js" },
  { pkg: "graphql", name: "GraphQL" },
  { pkg: "apollo-server", name: "Apollo Server" },
  { pkg: "@apollo/server", name: "Apollo Server" },
  { pkg: "@apollo/client", name: "Apollo Client" },
  { pkg: "trpc", name: "tRPC" },
  { pkg: "@trpc/server", name: "tRPC" },
  { pkg: "socket.io", name: "Socket.IO" },
  { pkg: "ws", name: "WebSocket" },
  { pkg: "tailwindcss", name: "Tailwind CSS" },
  { pkg: "bootstrap", name: "Bootstrap" },
  { pkg: "@mui/material", name: "Material UI" },
  { pkg: "antd", name: "Ant Design" },
  { pkg: "chakra-ui", name: "Chakra UI" },
  { pkg: "@chakra-ui/react", name: "Chakra UI" },
  { pkg: "redux", name: "Redux" },
  { pkg: "@reduxjs/toolkit", name: "Redux Toolkit" },
  { pkg: "zustand", name: "Zustand" },
  { pkg: "mobx", name: "MobX" },
  { pkg: "axios", name: "Axios" },
  { pkg: "typescript", name: "TypeScript" },
];

export const PYTHON_DEP_RULES = [
  { pkg: "django", name: "Django" },
  { pkg: "flask", name: "Flask" },
  { pkg: "fastapi", name: "FastAPI" },
  { pkg: "starlette", name: "Starlette" },
  { pkg: "tornado", name: "Tornado" },
  { pkg: "celery", name: "Celery" },
  { pkg: "uvicorn", name: "Uvicorn" },
  { pkg: "gunicorn", name: "Gunicorn" },
  { pkg: "pyramid", name: "Pyramid" },
  { pkg: "sanic", name: "Sanic" },
  { pkg: "aiohttp", name: "aiohttp" },
  { pkg: "streamlit", name: "Streamlit" },
  { pkg: "gradio", name: "Gradio" },
];

export const COMPOSER_DEP_RULES = [
  { pkg: "laravel/framework", name: "Laravel" },
  { pkg: "symfony/symfony", name: "Symfony" },
  { pkg: "symfony/http-foundation", name: "Symfony" },
  { pkg: "cakephp/cakephp", name: "CakePHP" },
  { pkg: "codeigniter4/framework", name: "CodeIgniter" },
  { pkg: "slim/slim", name: "Slim" },
];

export const GEM_RULES = [
  { pkg: "rails", name: "Ruby on Rails" },
  { pkg: "sinatra", name: "Sinatra" },
  { pkg: "hanami", name: "Hanami" },
];

export const GO_DEP_RULES = [
  { pkg: "github.com/gin-gonic/gin", name: "Gin" },
  { pkg: "github.com/labstack/echo", name: "Echo" },
  { pkg: "github.com/gofiber/fiber", name: "Fiber" },
  { pkg: "github.com/gorilla/mux", name: "Gorilla Mux" },
  { pkg: "github.com/go-chi/chi", name: "Chi" },
];

export const RUST_DEP_RULES = [
  { pkg: "actix-web", name: "Actix Web" },
  { pkg: "axum", name: "Axum" },
  { pkg: "rocket", name: "Rocket" },
  { pkg: "warp", name: "Warp" },
];

export const JAVA_CONTENT_RULES = [
  { match: /org\.springframework/i, name: "Spring" },
  { match: /spring-boot/i, name: "Spring Boot" },
  { match: /javax\.servlet|jakarta\.servlet/i, name: "Java Servlet" },
  { match: /micronaut/i, name: "Micronaut" },
  { match: /io\.quarkus/i, name: "Quarkus" },
];

export const DOTNET_CONTENT_RULES = [
  { match: /Microsoft\.AspNetCore/i, name: "ASP.NET Core" },
  { match: /Microsoft\.EntityFrameworkCore/i, name: "Entity Framework Core" },
  { match: /<Project\s+Sdk="Microsoft\.NET\.Sdk\.Web"/i, name: "ASP.NET Core" },
  { match: /Blazor/i, name: "Blazor" },
  { match: /MinimalApi|MapGet\(|MapPost\(/i, name: "ASP.NET Minimal APIs" },
];

export const FLUTTER_CONTENT_RULES = [
  { match: /flutter:/i, name: "Flutter" },
  { match: /package:flutter\//i, name: "Flutter" },
  { match: /package:flutter_riverpod/i, name: "Flutter Riverpod" },
  { match: /package:provider\//i, name: "Flutter Provider" },
  { match: /package:get\//i, name: "GetX" },
  { match: /package:bloc\//i, name: "Flutter Bloc" },
];

export const RN_SIGNAL_FILES = [
  /(?:^|\/)metro\.config\.(js|ts|cjs)$/i,
  /(?:^|\/)react-native\.config\.js$/i,
  /(?:^|\/)app\.json$/i,
];
